"""
data.py -- the data sets for Project 1.

PROVIDED.  Do not edit this file.

Every data set here is generated from a fixed seed, so everyone in the class
works with exactly the same numbers.  A data set of N points in R^2 is a NumPy
array with one point per row: X[i] is the i-th point, a vector [x, y].
"""

import numpy as np


# --------------------------------------------------------------------------
# Part 1 -- k-nearest neighbours
# --------------------------------------------------------------------------

def lecture_knn_example():
    """The eight labelled points and the query of computational unit Sec. 6.5.

    Returns X (8 points, one per row), y (their labels, "A" or "B") and the
    query q = [5, 5].  The lecture works out that k = 1 predicts "A" while
    k = 3 and k = 5 predict "B" -- use it to test knn_predict.
    """
    X = np.array([[1, 1], [2, 3], [2, 1], [4, 5],
                  [6, 4], [7, 6], [6, 8], [8, 5]], dtype=float)
    y = np.array(["A", "A", "A", "A", "B", "B", "B", "B"])
    q = np.array([5.0, 5.0])
    return X, y, q


def songs():
    """A music app's songs, each described by two numbers:

        [duration in seconds, energy on a scale from 0 to 1]

    and labelled with its genre: "lofi", "pop" or "metal".

    Returns X_train, y_train (150 songs, 50 per genre) and X_test, y_test
    (90 songs, 30 per genre).
    """
    rng = np.random.default_rng(231)
    #            mean duration, sd duration, mean energy, sd energy
    genres = {"lofi":  (200, 40, 0.25, 0.10),
              "pop":   (210, 40, 0.60, 0.10),
              "metal": (240, 50, 0.85, 0.07)}
    X_train, y_train, X_test, y_test = [], [], [], []
    for label, (md, sd, me, se) in genres.items():
        for n, X_part, y_part in ((50, X_train, y_train), (30, X_test, y_test)):
            duration = np.round(rng.normal(md, sd, n))
            energy = np.round(np.clip(rng.normal(me, se, n), 0.0, 1.0), 3)
            for d, e in zip(duration, energy):
                X_part.append([d, e])
                y_part.append(label)
    return (np.array(X_train), np.array(y_train),
            np.array(X_test), np.array(y_test))


# --------------------------------------------------------------------------
# Part 2 -- k-means
# --------------------------------------------------------------------------

def lecture_kmeans_example():
    """The six points of computational unit Sec. 12.5, and its bad start.

    Returns X (6 points, one per row) and the initial centres
    [1, 1] and [2, 1] -- both inside the left-hand group on purpose.
    """
    X = np.array([[1, 1], [2, 1], [1, 2],
                  [8, 8], [9, 8], [8, 9]], dtype=float)
    init_centres = np.array([[1, 1], [2, 1]], dtype=float)
    return X, init_centres


def city():
    """Home locations of 320 customers of a food-truck company, in km.

    The customers live in four neighbourhoods of different sizes.  Returns X,
    an array with one location [x, y] per row.
    """
    rng = np.random.default_rng(231)
    #                 centre       spread  how many
    neighbourhoods = [((2.0, 2.0), 0.70, 120),    # downtown
                      ((6.0, 2.0), 0.80,  70),    # university
                      ((2.5, 6.5), 0.80,  70),    # harbour
                      ((7.0, 7.0), 1.10,  60)]    # suburbs
    points = []
    for (cx, cy), spread, n in neighbourhoods:
        points.append(np.column_stack([rng.normal(cx, spread, n),
                                       rng.normal(cy, spread, n)]))
    X = np.vstack(points)
    return X[rng.permutation(len(X))]


def city_bad_start():
    """Four initial centres for the city data: three downtown, one at the
    university.  Task 2.5 shows what Lloyd's algorithm makes of it."""
    return np.array([[2.0, 2.2], [2.0, 1.8], [2.9, 2.7], [6.0, 2.5]])


def random_start(X, k, rng):
    """k distinct points of X chosen at random, to use as initial centres.

    This is the usual initialisation (computational unit Sec. 12.3, line 1).
    """
    rows = rng.choice(len(X), size=k, replace=False)
    return X[rows].copy()


# --------------------------------------------------------------------------
# Part 3 -- gradient descent
# --------------------------------------------------------------------------

def marble_starts():
    """Five starting points for Task 3.3."""
    return [np.array(p) for p in
            [(0.5, 0.5), (2.5, -4.0), (5.0, 1.0), (-3.0, 3.0), (-2.0, -4.0)]]


def census_starts():
    """500 random starting points in the square [-6, 6] x [-6, 6], Task 3.5."""
    rng = np.random.default_rng(231)
    return rng.uniform(-6.0, 6.0, size=(500, 2))
