"""
runproject1.py -- runs the steps of your choice in Project 1, in order.

PROVIDED.  Do not edit this file.  It is what the grader runs.

    python runproject1.py            the choice named by TRACK in project1.py
    python runproject1.py kmeans     a different choice: knn, kmeans or descent
    python runproject1.py all        all three choices

The grader runs the first form, so the choice that is graded is the one TRACK
names.  If TRACK is not set, all three choices run, with a reminder to set it.

It prints one labelled block per step and saves figures into a folder named
figures/ next to this file.  It never opens a window: the live animations are
in play.py.  A step whose function still raises NotImplementedError is reported
as "not implemented yet"; a step whose code crashes is reported with the error,
and the run carries on.
"""

import os
import sys
import traceback

import matplotlib
matplotlib.use("Agg")                  # save figures only, never open windows

import numpy as np

import data
import viz
import project1 as p1

np.set_printoptions(precision=4, suppress=True)
HERE = os.path.dirname(os.path.abspath(__file__))
FIG = os.path.join(HERE, "figures")
os.makedirs(FIG, exist_ok=True)


def fig(name):
    return os.path.join(FIG, name)


# --------------------------------------------------------------------------
# Which choice to run
# --------------------------------------------------------------------------

CHOICES = {"knn": "1", "kmeans": "2", "descent": "3"}
NAMES = {"1": "k-nearest neighbours", "2": "k-means", "3": "gradient descent"}


def _selected():
    """The choice numbers to run, from the command line or else from TRACK."""
    if len(sys.argv) > 1:
        choice = sys.argv[1].strip().lower()
        if choice == "all":
            return set(CHOICES.values())
        if choice in CHOICES:
            return {CHOICES[choice]}
        sys.exit(f"Unknown choice {sys.argv[1]!r}: use knn, kmeans, descent "
                 f"or all.")
    track = str(getattr(p1, "TRACK", "")).strip().lower()
    if track in CHOICES:
        return {CHOICES[track]}
    if track:
        print(f"TRACK = {track!r} in project1.py is not one of "
              f"\"knn\", \"kmeans\", \"descent\".")
    else:
        print("TRACK is not set in project1.py.")
    print("Running all three choices.  Set TRACK to the choice you made: "
          "only that choice is graded.")
    return set(CHOICES.values())


CHOSEN = _selected()
for choice in sorted(CHOSEN):
    print(f"Choice {choice} -- {NAMES[choice]}")


def step(label):
    """Decorator: print the label, run the step, report problems, carry on.

    Steps of the other choices are skipped without printing anything.
    """
    def wrap(fn):
        if label.split(".")[0] not in CHOSEN:
            return fn
        print(f"\nOutput of step {label} :")
        try:
            fn()
        except NotImplementedError:
            print("    not implemented yet")
        except Exception:
            last = traceback.format_exc().strip().splitlines()[-1]
            print(f"    ERROR -- {last}")
        return fn
    return wrap


# ==========================================================================
# Choice 1 -- k-nearest neighbours          (TRACK = "knn")
# ==========================================================================

@step("1.1")
def _():
    x, y = np.array([1.0, 1.0]), np.array([4.0, 5.0])
    for p in (1, 2, np.inf):
        print(f"    distance([1, 1], [4, 5], p={p}) = {p1.distance(x, y, p)}")


@step("1.2")
def _():
    X, y, q = data.lecture_knn_example()
    for k in (1, 3, 5):
        print(f"    lecture example, query [5, 5], k={k}: "
              f"{p1.knn_predict(X, y, q, k)}")


@step("1.3")
def _():
    Xtr, ytr, Xte, yte = data.songs()
    for k in (1, 3, 5, 9, 15):
        a = p1.accuracy(Xtr, ytr, Xte, yte, k)
        print(f"    raw features,    k={k:2d}: accuracy {a:.3f}")


@step("1.4")
def _():
    Xtr, ytr, Xte, yte = data.songs()
    print(f"    raw training means: {Xtr.mean(axis=0)}   "
          f"standard deviations: {Xtr.std(axis=0)}")
    Ztr, Zte = p1.standardize(Xtr, Xte)
    print(f"    scaled training means: {Ztr.mean(axis=0)}   "
          f"standard deviations: {Ztr.std(axis=0)}")
    for k in (1, 3, 5, 9, 15):
        a = p1.accuracy(Ztr, ytr, Zte, yte, k)
        print(f"    scaled features, k={k:2d}: accuracy {a:.3f}")


@step("1.5")
def _():
    Xtr, ytr, Xte, yte = data.songs()
    Ztr, Zte = p1.standardize(Xtr, Xte)
    for p in (1, 2, np.inf):
        a = p1.accuracy(Ztr, ytr, Zte, yte, 9, p)
        print(f"    scaled features, k=9, p={p}: accuracy {a:.3f}")
    viz.plot_decision_regions(
        lambda q: p1.knn_predict(Xtr, ytr, q, 15), Xtr, ytr,
        "k = 15, raw features", fig("knn_raw_k15.png"),
        xlabel="duration (s)", ylabel="energy")
    for k in (1, 15):
        viz.plot_decision_regions(
            lambda q, k=k: p1.knn_predict(Ztr, ytr, q, k), Ztr, ytr,
            f"k = {k}, standardized features", fig(f"knn_scaled_k{k}.png"),
            xlabel="duration (standardized)", ylabel="energy (standardized)")
    print("    saved figures/knn_raw_k15.png, knn_scaled_k1.png, "
          "knn_scaled_k15.png")


# ==========================================================================
# Choice 2 -- k-means                       (TRACK = "kmeans")
# ==========================================================================

@step("2.1")
def _():
    X, C = data.lecture_kmeans_example()
    print(f"    lecture example, first assignment: {p1.assign(X, C)}")


@step("2.2")
def _():
    X, C = data.lecture_kmeans_example()
    labels = p1.assign(X, C)
    print("    lecture example, centres after the first update:")
    print("   ", str(p1.update(X, labels, C)).replace("\n", "\n    "))


@step("2.3")
def _():
    X, C = data.lecture_kmeans_example()
    labels = p1.assign(X, C)
    print(f"    J at the start:            {p1.wcss(X, labels, C):.4f}")
    C1 = p1.update(X, labels, C)
    print(f"    J after the first update:  {p1.wcss(X, labels, C1):.4f}")


@step("2.4")
def _():
    X, C = data.lecture_kmeans_example()
    centres, labels, history = p1.kmeans(X, C)
    print(f"    lecture example: labels {labels}, J history "
          f"{[round(float(J), 4) for J in history]}")
    print("    final centres:")
    print("   ", str(centres).replace("\n", "\n    "))
    X = data.city()
    centres, labels, history = p1.kmeans(X, data.random_start(
        X, 4, np.random.default_rng(231)))
    hist = [round(float(J), 2) for J in history]
    print(f"    city, k=4, random start: {len(history)} passes, J history {hist}")
    print(f"    J never increased: "
          f"{all(b <= a + 1e-9 for a, b in zip(history, history[1:]))}")
    viz.plot_clusters(X, labels, centres, f"k = 4,  J = {history[-1]:.2f}",
                      fig("kmeans_city_k4.png"))
    print("    saved figures/kmeans_city_k4.png")


@step("2.5")
def _():
    X = data.city()
    centres, labels, history = p1.kmeans(X, data.city_bad_start())
    print(f"    city, k=4, three centres start downtown: final J "
          f"{history[-1]:.2f}")
    viz.plot_clusters(X, labels, centres,
                      f"bad start:  J = {history[-1]:.2f}",
                      fig("kmeans_city_bad_start.png"))
    rng = np.random.default_rng(231)
    finals = [p1.kmeans(X, data.random_start(X, 4, rng))[2][-1]
              for _ in range(10)]
    print(f"    10 random starts, final J: {[round(float(J), 2) for J in finals]}")
    print(f"    best of 10: {min(finals):.2f}")
    ks, best = list(range(1, 9)), []
    for k in ks:
        best.append(min(p1.kmeans(X, data.random_start(X, k, rng))[2][-1]
                        for _ in range(10)))
    print(f"    elbow, best J for k = 1..8: {[round(float(J), 1) for J in best]}")
    viz.plot_elbow(ks, best, fig("kmeans_elbow.png"))
    print("    saved figures/kmeans_city_bad_start.png, kmeans_elbow.png")


# ==========================================================================
# Choice 3 -- gradient descent              (TRACK = "descent")
# ==========================================================================

@step("3.1")
def _():
    for p in ([0.0, 0.0], [1.0, 2.0], [-1.0, 0.5]):
        print(f"    grad_f({p}) = {p1.grad_f(np.array(p))}")
    rng = np.random.default_rng(0)
    h, worst = 1e-6, 0.0
    for _ in range(50):
        p = rng.uniform(-6, 6, size=2)
        numeric = np.array([(p1.f(p + [h, 0]) - p1.f(p - [h, 0])) / (2 * h),
                            (p1.f(p + [0, h]) - p1.f(p - [0, h])) / (2 * h)])
        worst = max(worst, float(np.max(np.abs(numeric - p1.grad_f(p)))))
    print(f"    largest disagreement with a numerical gradient at 50 random "
          f"points: {worst:.2e}")


@step("3.2")
def _():
    bowl = lambda p: 2 * np.asarray(p, dtype=float)     # grad of x^2 + y^2
    path, ok = p1.gradient_descent(bowl, np.array([1.0, 2.0]), 0.1)
    print(f"    x^2 + y^2 from [1, 2], lr = 0.1: first points "
          f"{[np.round(q, 4).tolist() for q in path[:4]]}")
    print(f"    converged: {ok}, after {len(path) - 1} steps")
    path, ok = p1.gradient_descent(bowl, np.array([1.0, 2.0]), 1.0,
                                   max_iter=20)
    print(f"    same, lr = 1.0, cap 20: converged {ok}, last point "
          f"{np.round(path[-1], 4)}")


@step("3.3")
def _():
    paths = []
    for s in data.marble_starts():
        path, ok = p1.gradient_descent(p1.grad_f, s, 0.3, max_iter=2000)
        paths.append(path)
        e = path[-1]
        print(f"    start {s}: end {np.round(e, 4)}, f = {p1.f(e):.4f}, "
              f"{len(path) - 1} steps, converged {ok}")
    viz.plot_landscape(p1.f, filename=fig("landscape.png"))
    viz.watch_descent(p1.f, paths, title="Five marbles, lr = 0.3",
                      filename=fig("marbles.png"))
    print("    saved figures/landscape.png, marbles.png")


@step("3.4")
def _():
    start = np.array([3.0, 1.5])
    for lr in (0.01, 0.1, 0.5, 1.0, 1.5, 2.0):
        path, ok = p1.gradient_descent(p1.grad_f, start, lr)
        e = path[-1]
        print(f"    start [3, 1.5], lr = {lr:4}: converged {str(ok):5}, "
              f"{len(path) - 1:4d} steps, end {np.round(e, 3)}, "
              f"f = {p1.f(e):.4f}")
    start = np.array([-4.0, 4.6])
    paths = []
    for lr in (0.1, 1.5):
        path, ok = p1.gradient_descent(p1.grad_f, start, lr)
        paths.append(path)
        e = path[-1]
        print(f"    start [-4, 4.6], lr = {lr}: end {np.round(e, 3)}, "
              f"f = {p1.f(e):.4f}")
    viz.watch_descent(p1.f, paths, names=["lr = 0.1", "lr = 1.5"],
                      title="One start, two learning rates",
                      filename=fig("learning_rates.png"))
    print("    saved figures/learning_rates.png")


print()
